# Make processor dependent startup and libraries

# $Id$

ARMSRC		?= ..
MCUFAMILY	= at91sam7s
BOARDNAME	?= OLIMEX_SAM7_P256

include $(ARMSRC)/include/ARM.mk

.PHONY: clean reallyclean distclean

clean: ARM_mk_clean

reallyclean: clean

distclean: reallyclean
