# Make processor dependent startup and libraries

# $Id: Makefile,v 1.5 2008-07-01 19:07:24 cvs Exp $

ARMSRC		= ..
MCU             = at91sam7s256

default: lib$(MCU).a

include $(ARMSRC)/include/ARM.mk
