# Make processor dependent startup and libraries

# $Id$

ARMSRC		?= ..
MCUFAMILY	= lpc11xx

BOARDNAME	?= PROTOBOARD
#BOARDNAME	?= RASPBERRYPI_LPC1114

include $(ARMSRC)/include/ARM.mk

.PHONY: clean reallyclean distclean

clean: ARM_mk_clean

reallyclean: clean

distclean: reallyclean
