# Make processor dependent startup and libraries

# $Id$

ARMSRC		?= ..
MCUFAMILY	= lpc11xx

BOARDNAME	?= LPC1114FN28

include $(ARMSRC)/include/ARM.mk

.PHONY: clean reallyclean distclean

clean: ARM_mk_clean

reallyclean: clean

distclean: reallyclean
