# Make processor dependent startup and libraries

# $Id$

ARMSRC		?= ..
MCUFAMILY	= lpc17xx
BOARDNAME	?= MBED_LPC1768
#BOARDNAME	?= BLUEBOARD_LPC1768_H

include $(ARMSRC)/include/ARM.mk

.PHONY: clean reallyclean distclean

clean: ARM_mk_clean

reallyclean: clean

distclean: reallyclean
