# Make processor dependent startup and libraries

# $Id$

ARMSRC		= ..
MCUFAMILY	= lpc17xx
MCU		= $(MCUFAMILY)
BOARDNAME	?= MBED_LPC1768
#BOARDNAME	?= BLUEBOARD_LPC1768_H

default: lib$(MCU).a

include $(ARMSRC)/include/ARM.mk
