# Make processor dependent startup and libraries

# $Id: Makefile,v 1.6 2008-07-01 20:39:17 cvs Exp $

ARMSRC		= ..
MCU             = stm32f103

default: lib$(MCU).a

include $(ARMSRC)/include/ARM.mk
