# Make processor dependent startup and libraries

# $Id$

ARMSRC		?= ..
MCUFAMILY	= str91x
BOARDNAME	?= STMICRO_STR910_EVAL

include $(ARMSRC)/include/ARM.mk

.PHONY: clean reallyclean distclean

clean: ARM_mk_clean

reallyclean: clean

distclean: reallyclean
