# Make processor dependent startup and libraries

# $Id$

ARMSRC		= ..
MCUFAMILY	= lpc23xx
MCU		= $(MCUFAMILY)
BOARDNAME	?= MBED_LPC2368
#BOARDNAME	?= OLIMEX_LPC_P2378

default: lib$(MCU).a

include $(ARMSRC)/include/ARM.mk
