# Make processor dependent startup and libraries

# $Id$

ARMSRC		?= ..
MCUFAMILY	= lpc23xx
BOARDNAME	?= MBED_LPC2368
#BOARDNAME	?= OLIMEX_LPC_P2378

include $(ARMSRC)/include/ARM.mk

.PHONY: clean reallyclean distclean

clean: ARM_mk_clean

reallyclean: clean

distclean: reallyclean
