# Makefile for processor independent demo programs

# $Id$

ARMSRC		?= ..
MCUFAMILY	?= stm32f4
BOARDNAME	?= STM32F4_DISCOVERY

include $(ARMSRC)/include/ARM.mk

.PHONY: clean reallyclean distclean

clean: ARM_mk_clean

reallyclean: clean

distclean: reallyclean
