#!/usr/bin/expect -f

# expect script for resetting the LPC2119 target

# $Id$

# Script arguments:

#   OpenOCD program file
#   OpenOCD configuration file

set OPENOCDPGM [lindex $argv 0]
set OPENOCDCFG [lindex $argv 1]
set prompt "> "
set timeout 10

spawn "$OPENOCDPGM" -f "$OPENOCDCFG"
expect -re "^.*Barf Nader.*$"
flush stdout

spawn /usr/bin/telnet localhost 4444
expect $prompt

send "reset run\n"
expect $prompt

exp_sleep 1

send "shutdown\n"
expect $prompt

exp_sleep 1
