#!/bin/sh

# Helper script for udev rule for BlueBoard LPC1768-H USB boot loader

# $Id$

# Add device

if [ "$ACTION" = "add" -a -n "$ID_FS_LABEL_ENC" ]; then
  ln -s -f "/media/`printf $ID_FS_LABEL_ENC`" /media/BLUEBOARD
fi

# Remove device

if [ "$ACTION" = "remove" -a -L /media/BLUEBOARD ]; then
  echo "Removing /media/BLUEBOARD" >> /tmp/bb.txt
  rm /media/BLUEBOARD 2>&1 >>/tmp/bb.txt
fi
