# Make processor dependent startup and libraries

# $Id$

ARMSRC		= ..
MCUFAMILY	= stm32
MCU             ?= stm32f103rb
BOARDNAME	?= OLIMEX_STM32_P103

default: lib$(MCU).a

include $(ARMSRC)/include/ARM.mk
